version: '3.9'

services:
  auth-service:
    build:
      context: ./auth-service
    image: auth-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://user:password@auth-db:5432/auth
    depends_on:
      - auth-db

  movies-service:
    build:
      context: ./movies-service
    image: movies-service
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://user:password@movies-db:5432/movies
    depends_on:
      - movies-db

  frontend:
    build:
      context: ./frontend
    image: frontend
    ports:
      - "3001:3000"
    environment:
      - API_AUTH_URL=http://auth-service:5000
      - API_MOVIES_URL=http://movies-service:5000
    depends_on:
      - auth-service
      - movies-service

  auth-db:
    image: postgres:17
    container_name: auth-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth
    volumes:
      - auth-data:/var/lib/postgresql/data
      - ./postgres/auth-init.sql:/docker-entrypoint-initdb.d/auth-init.sql

  movies-db:
    image: postgres:17
    container_name: movies-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=movies
    volumes:
      - movies-data:/var/lib/postgresql/data
      - ./postgres/movies-init.sql:/docker-entrypoint-initdb.d/movies-init.sql

volumes:
  auth-data:
  movies-data:
