# ConfigMaps for auth service/db
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  PORT: "5000"
  DATABASE_URL: "postgres://user:password@auth-db-service:5432/auth"
    # USER: user
    # PASSWORD: password
    # DB: auth
    # HOST: auth-db
  POSTGRES_USER : "user"
  POSTGRES_PASSWORD : "password"
  POSTGRES_DB : "auth"