# ConfigMaps for movies service/db
apiVersion: v1
kind: ConfigMap
metadata:
  name: movies-config
data:
  DATABASE_URL: "postgres://user:password@movies-db:5432/movies"
  POSTGRES_USER : "user"
  POSTGRES_PASSWORD : "password"
  POSTGRES_DB : "movies"