# ConfigMaps for movies service/db
apiVersion: v1
kind: ConfigMap
metadata:
  name: movies-config
  namespace: production
data:
  PORT: "5000"
  DATABASE_URL: "postgres://user:password@movies-db-service:5432/movies"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "movies"
