apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
spec:
  serviceName: "auth-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: auth-db
          image: postgres:17
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: auth-config
          volumeMounts:
            - name: auth-data
              mountPath: /var/lib/postgresql/data
            - name: auth-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: auth-init
          configMap:
            name: auth-sql-config
  volumeClaimTemplates:
    - metadata:
        name: auth-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
