apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: auth-db
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: auth-config
          volumeMounts:
            - name: auth-data
              mountPath: /var/lib/postgresql/data  # Montez le PVC ici
            - name: auth-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: auth-data
          persistentVolumeClaim:
            claimName: auth-db-pvc
        - name: auth-init
          configMap:
            name: auth-init-config


