apiVersion: apps/v1 
kind: Deployment
metadata:
  name: films-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: films-service
  template:
    metadata:
      labels:
        app: films-service
    spec:
      containers:
      - name: films-service
        image: films-service
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: films-config

