apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movies-db
  namespace: production
spec:
  serviceName: movies-db-service
  replicas: 1
  selector:
    matchLabels:
      app: movies-db
  template:
    metadata:
      labels:
        app: movies-db
    spec:
      containers:
        - name: movies-db
          image: postgres:17
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: movies-config
          volumeMounts:
            # - name: movies-data
            #   mountPath: /var/lib/postgresql/data
            - name: movies-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: movies-init
          configMap:
            name: movies-sql-config
  volumeClaimTemplates:
    - metadata:
        name: movies-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
