apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-db
  template:
    metadata:
      labels:
        app: movies-db
    spec:
      containers:
      - name: movies-db
        image: postgres:17
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: movies-config
        volumeMounts:
        - name: movies-data
          mountPath: /var/lib/postgresql/data
        - name: movies-init
          mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: movies-data
          persistentVolumeClaim:
            claimName: movies-db-pvc
        - name: movies-init
          configMap:
            name: movies-init-config
