apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service  # Sélectionne les pods avec l'étiquette 'app: auth-service'
  ports:
    - protocol: TCP
      port: 5000    # Le port exposé sur le service
      targetPort: 5000  # Le port du container à atteindre
  type: NodePort  # Expose le service sur un port aléatoire de l'hôte
