apiVersion: v1
kind: Service
metadata:
  name: frontend-external
  namespace: production
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # Le port externe exposé
      targetPort: 3000 # Le port du container à atteindre
  type: NodePort # Permet d'exposer le service à l'extérieur du cluster
