apiVersion: v1
kind: Service
metadata:
  name: movies-db-service
  namespace: production
spec:
  selector:
    app: movies-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
